import type { NextPage } from 'next'
import Head from 'next/head'
import { AboutUs, Contact, Landing, Menu, Navbar } from '../components'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={styles.home} id="home">
        <Navbar  lang={"en"} />
        <Landing lang={"en"} />

        </section>

        {/* <SectionBreak /> */}
        <AboutUs lang={"en"} />
        <Menu lang={"en"} />
        <Contact lang={"en"} />
      </main>

      
    </div>
  )
}

export default Home
